### PR TITLE
Switch from babel-preset-es2015 to babel-preset-env

### PR DESCRIPTION
**Pull request by cherewaty**
Eliminates this warning:
```
warning babel-preset-es2015@6.24.1: We're super 😸  excited that you're trying to use ES2015 syntax, but instead of continuing yearly presets 😭 , we recommend using babel-preset-env: npm install babel-preset-env. preset-env without options will compile ES2015+ down to ES5. And by targeting specific browsers, Babel can do less work and you can ship native ES2015+ to users 😎 ! Also, we are in the process of releasing v7, so give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and test it! Thanks so much for using Babel 🙏 , please give us a follow @babeljs for updates, join slack.babeljs.io for discussion and help support at opencollective.com/babel
```

### CODE REVIEW

**Comment by Turbo87** [comment]
@cherewaty does this work correctly without specifying what target envs we have?

**Comment by cherewaty** [comment]
Yes, it should. Without any configuration options, it behaves exactly like `babel-preset-latest`, which will compile anything from the es2015, es2016, or es2017 babel presets down to ES5.

**Comment by Turbo87** [comment]
cool, thanks!

**Comment by Turbo87** [comment]
released as `v0.4.3`

**Pull request merged**
