### PR TITLE
Update "ember-cli-babel" to v6.1.0

### PR DESCRIPTION
**Pull request by Turbo87**

### CODE REVIEW

**Comment by polarctos** [comment]
Is it possible that the usage of the old Babel version is blocking `ember-cli-chai v0.3.2` usage 
with `ember-cli v2.13.1` in `phantomjs v2.1.14`?

Tests run fine in Chrome though.

Or is that unrelated?

```
<error message="
Died on test #1 moduleLoadFailure@http://localhost:10001/assets/test-support.js:15093:28
http://localhost:10001/assets/test-support.js:15321:33
require@http://localhost:10001/assets/test-support.js:15309:32
loadModules@http://localhost:10001/assets/test-support.js:15301:23
loadTests@http://localhost:10001/assets/test-support.js:15146:33
start@http://localhost:10001/assets/test-support.js:15181:16
http://localhost:10001/assets/tests.js:1194:28
exports@http://localhost:10001/assets/vendor.js:119:37
requireModule@http://localhost:10001/assets/vendor.js:34:25
global code@http://localhost:10001/assets/tests.js:1262:8: Object is not a constructor (evaluating '(0, _lodash_defineProperty['default'])')
">
```

**Comment by Turbo87** [comment]
@polarctos no, that is an issue in ember-lodash as far as I know, but has nothing to do with ember-cli-chai.

**Comment by polarctos** [comment]
Thanks for the quick response. I created an issue there: https://github.com/mike-north/ember-lodash/issues/103

**Comment by Turbo87** [comment]
@rwjblue good catch, fixed

**Pull request merged**
